[package]
name = "speech"
version = "0.2.1"
edition = "2021"

[lib]
name = "speech"
crate-type = ["cdylib"]

[dependencies]
vad-core = { path = "../core" }
ffrwd-node = { git = "https://github.com/imbcmdth/ffrwd-node", tag = "v0.2.0" }
wit-bindgen = "0.57.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
